#
# Docker-Compose file
# ===================
#
# This file is used to run the postgresql database inside docker.
# 

version: '2'

services:
  postgres:
    image: "postgres:9.6.0"
    ports:
      - "5432:5432"
    volumes:
      - "./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh"
      - "./fixtures:/fixtures"
    environment:
      - "POSTGRES_DB=world"
      - "POSTGRES_USER=meetup"
      - "POSTGRES_PASSWORD=scala"


